name:                write-scheme
version:             0.1.0.0
github:              "zarak/write-scheme"
license:             BSD3
author:              "Zarak"
maintainer:          "zarak@hotmail.ca"
copyright:           "2020 Zarak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zarak/write-scheme#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  write-scheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - write-scheme

tests:
  write-scheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - write-scheme
    - hspec
    - QuickCheck
